language: cpp
group: travis_latest
sudo: false
cache: ccache
script: cmake

branches:
  only:
  - dev

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qt5-default
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo pip install cmake
  - which $CXX
  - $CXX --version
  - which $CC
  - $CC --version
  - which cmake
  - cmake --version

before_script:
- mkdir -p build/{debug,release}
- cd build/debug
- cmake -DCMAKE_BUILD_TYPE=Debug ../..
- cd ../release
- cmake -DCMAKE_BUILD_TYPE=Release ../..
- cd ..

script:
  - cd debug
  - cmake --build . -- -j2
  - cd ../release
  - cmake --build . -- -j2