version: 0.1.{build}
image: Visual Studio 2017

configuration:
- Release
- Debug

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.11\msvc2017_64

build:
  project: c:\projects\Fennec\build\Fennec.sln
  verbosity: minimal
  parallel: true

test_script:
  - ctest -V -j 2 -T Test
  - ps: |
        $TestTag = Get-Content .\Testing\TAG -First 1
        $XslPath = Resolve-Path -Path ".\..\ctest-to-junit.xsl"
        $TestResultFilePath = Resolve-Path -Path ".\Testing\$TestTag\Test.xml"
        $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
        $XSLInputElement.Load($XslPath)
        $XSLInputElement.Transform($TestResultFilePath, (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))
