version: 0.1.{build}
image: Visual Studio 2017
test: off

configuration:
- Release
- Debug

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.11\msvc2017_64

build:
  project: c:\projects\Fennec\build\Fennec.sln
  verbosity: minimal
  parallel: true
